# Generated by Django 2.0.3 on 2018-04-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('label',)},
        ),
    ]
